# Generated by Django 4.2.23 on 2025-08-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0002_timerstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
