# Generated by Django 4.2.23 on 2025-08-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0003_routine_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerstate',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timerstate',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
