# Generated by Django 4.2.23 on 2025-08-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0004_timerstate_end_time_timerstate_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerstate',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
